### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by makeconfig2017** [technology16/pgsqlblocks#53]
Hello,

The program crashes while running with error:
![pgsqlblocks_1_7_3](https://user-images.githubusercontent.com/26453996/83773203-ea9cd380-a68c-11ea-97d1-7d12c17ef443.png)
in log files there is messages like:
`2020-06-04T17:34:37,447 [pool-24-thread-1] ERROR ru.taximaxim.pgsqlblocks.modules.db.controller.DBController [] - ?????? ??? ????????? ????????? ??? localhost.local
org.postgresql.util.PSQLException: Ran out of memory retrieving query results.
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2212) ~[pgSqlBlocks-1.7.3-Linux-64.jar:1.7.3]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311) ~[pgSqlBlocks-1.7.3-Linux-64.jar:1.7.3]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447) ~[pgSqlBlocks-1.7.3-Linux-64.jar:1.7.3]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368) ~[pgSqlBlocks-1.7.3-Linux-64.jar:1.7.3]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159) ~[pgSqlBlocks-1.7.3-Linux-64.jar:1.7.3]
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109) ~[pgSqlBlocks-1.7.3-Linux-64.jar:1.7.3]
        at ru.taximaxim.pgsqlblocks.modules.db.controller.DBController.loadProcesses(DBController.java:291) ~[pgSqlBlocks-1.7.3-Linux-64.jar:1.7.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.OutOfMemoryError: Java heap space
`
`Exception occurred
java.lang.ArrayIndexOutOfBoundsException
Exception occurred
java.lang.ArrayIndexOutOfBoundsException
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalArgumentException: Argument not valid)
        at org.eclipse.swt.SWT.error(SWT.java:4720)
        at org.eclipse.swt.SWT.error(SWT.java:4635)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4910)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4432)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
        at org.eclipse.jface.window.Window.open(Window.java:799)
        at ru.taximaxim.pgsqlblocks.modules.application.view.ApplicationView.show(ApplicationView.java:85)
        at ru.taximaxim.pgsqlblocks.modules.application.controller.ApplicationController.launch(ApplicationController.java:45)
        at ru.taximaxim.pgsqlblocks.PgSqlBlocks.launch(PgSqlBlocks.java:49)
        at ru.taximaxim.pgsqlblocks.PgSqlBlocks.main(PgSqlBlocks.java:35)
Caused by: java.lang.IllegalArgumentException: Argument not valid
        at org.eclipse.swt.SWT.error(SWT.java:4701)
        at org.eclipse.swt.SWT.error(SWT.java:4635)
        at org.eclipse.swt.SWT.error(SWT.java:4606)
        at org.eclipse.swt.custom.DefaultContent.error(DefaultContent.java:682)
        at org.eclipse.swt.custom.DefaultContent.getOffsetAtLine(DefaultContent.java:652)
        at org.eclipse.swt.custom.StyledTextRenderer.textChanging(StyledTextRenderer.java:1764)
        at org.eclipse.swt.custom.StyledText.handleTextChanging(StyledText.java:6436)
        at org.eclipse.swt.custom.StyledText$5.textChanging(StyledText.java:5770)
        at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:80)
        at org.eclipse.swt.custom.DefaultContent.sendTextEvent(DefaultContent.java:810)
        at org.eclipse.swt.custom.DefaultContent.replaceTextRange(DefaultContent.java:794)
        at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7433)
        at org.eclipse.swt.custom.StyledText.replaceTextRange(StyledText.java:8056)
        at org.eclipse.swt.custom.StyledText.append(StyledText.java:1534)
        at ru.taximaxim.pgsqlblocks.modules.logs.view.LogsView.lambda$new$1(LogsView.java:57)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
        ... 8 more
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.OutOfMemoryError: Java heap space)
        at org.eclipse.swt.SWT.error(SWT.java:4720)
        at org.eclipse.swt.SWT.error(SWT.java:4635)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4910)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4432)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
        at org.eclipse.jface.window.Window.open(Window.java:799)
        at ru.taximaxim.pgsqlblocks.modules.application.view.ApplicationView.show(ApplicationView.java:85)
        at ru.taximaxim.pgsqlblocks.modules.application.controller.ApplicationController.launch(ApplicationController.java:45)
        at ru.taximaxim.pgsqlblocks.PgSqlBlocks.launch(PgSqlBlocks.java:49)
        at ru.taximaxim.pgsqlblocks.PgSqlBlocks.main(PgSqlBlocks.java:35)
Caused by: java.lang.OutOfMemoryError: Java heap space
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalArgumentException: Argument not valid)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
`

**Comment by makeconfig2017** [comment]
After running the program with parameters:
java -Xmx2G -jar pgSqlBlocks.jar
Getting the error:
![Screenshot_20200630_094752](https://user-images.githubusercontent.com/26453996/86093623-ee6b1c80-bab7-11ea-8b26-ace9fd5a258a.png)
Here is the log:
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalArgumentException: Argument not valid)
        at org.eclipse.swt.SWT.error(SWT.java:4720)
        at org.eclipse.swt.SWT.error(SWT.java:4635)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4910)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4432)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
        at org.eclipse.jface.window.Window.open(Window.java:799)
        at ru.taximaxim.pgsqlblocks.modules.application.view.ApplicationView.show(ApplicationView.java:85)
        at ru.taximaxim.pgsqlblocks.modules.application.controller.ApplicationController.launch(ApplicationController.java:45)
        at ru.taximaxim.pgsqlblocks.PgSqlBlocks.launch(PgSqlBlocks.java:49)
        at ru.taximaxim.pgsqlblocks.PgSqlBlocks.main(PgSqlBlocks.java:35)
Caused by: java.lang.IllegalArgumentException: Argument not valid
        at org.eclipse.swt.SWT.error(SWT.java:4701)
        at org.eclipse.swt.SWT.error(SWT.java:4635)
        at org.eclipse.swt.SWT.error(SWT.java:4606)
        at org.eclipse.swt.custom.DefaultContent.error(DefaultContent.java:682)
        at org.eclipse.swt.custom.DefaultContent.getOffsetAtLine(DefaultContent.java:652)
        at org.eclipse.swt.custom.StyledTextRenderer.textChanging(StyledTextRenderer.java:1764)
        at org.eclipse.swt.custom.StyledText.handleTextChanging(StyledText.java:6436)
        at org.eclipse.swt.custom.StyledText$5.textChanging(StyledText.java:5770)
        at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:80)
        at org.eclipse.swt.custom.DefaultContent.sendTextEvent(DefaultContent.java:810)
        at org.eclipse.swt.custom.DefaultContent.replaceTextRange(DefaultContent.java:794)
        at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7433)
        at org.eclipse.swt.custom.StyledText.replaceTextRange(StyledText.java:8056)
        at org.eclipse.swt.custom.StyledText.append(StyledText.java:1534)
        at ru.taximaxim.pgsqlblocks.modules.logs.view.LogsView.lambda$new$1(LogsView.java:57)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
        ... 8 more

**Comment by Endeavourl** [comment]
Как часто происходит такая ошибка? Сколько программа работает до такой ошибки? Если возможно, оцените количество логов, которое программа записала с момента запуска до ошибки.

**Comment by makeconfig2017** [comment]
Зависает спустя 5-6 дней с момента запуска, завешивает CPU на 100% и перестает работать. Размер логов перед запуском:
105M    .pgSqlBlocks/log
48M     .pgSqlBlocks/blocksJournals
после аварийной остановки:
106M    .pgSqlBlocks/log
52M     .pgSqlBlocks/blocksJournals
во вложении лог ошибок
[pgsqlblocks_err.txt](https://github.com/technology16/pgsqlblocks/files/5160711/pgsqlblocks_err.txt)

**Comment by Endeavourl** [comment]
@makeconfig2017 по возможности попробуйте дождаться воспроизведения этой ошибки, запустив Java с параметром `-XX:+HeapDumpOnOutOfMemoryError`, и полученный дамп памяти отправить мне на levsha_aa@taximaxim.ru (скорее всего через дропбокс или другое облако, файл большой). Для ускорения воспроизведения и уменьшения размера файла можно запустить Java с параметром `-Xmx256M`.

Для работы в стабильной среде можно пока использовать версию 1.7.0, последнюю до появления этой утечки памяти.

**Comment by AXEPOH** [comment]
Исправлено в c838c08
