### ISSUE TITLE
Could not start on OpenSUSE 42.2 x64

### ISSUE THREAD

**Issue by antonhead** [technology16/pgsqlblocks#9]
Fails to start with exception:
`java.lang.NullPointerException 
        at org.eclipse.swt.widgets.TabFolder.gtk_switch_page(Unknown Source) 
        at org.eclipse.swt.widgets.Widget.windowProc(Unknown Source) 
        at org.eclipse.swt.widgets.Display.windowProc(Unknown Source) 
        at org.eclipse.swt.internal.gtk.OS._gtk_widget_show(Native Method) 
        at org.eclipse.swt.internal.gtk.OS.gtk_widget_show(Unknown Source) 
        at org.eclipse.swt.widgets.TabFolder.createItem(Unknown Source) 
        at org.eclipse.swt.widgets.TabItem.createWidget(Unknown Source) 
        at org.eclipse.swt.widgets.TabItem.<init>(Unknown Source) 
        at ru.taximaxim.pgsqlblocks.MainForm.createContents(MainForm.java:200) 
        at org.eclipse.jface.window.Window.create(Window.java:430) 
        at org.eclipse.jface.window.Window.open(Window.java:792) 
        at ru.taximaxim.pgsqlblocks.MainForm.main(MainForm.java:104)`

**Comment by antonhead** [comment]
Seems to be SWT bug, quick fix is to use gtk2. Set this env variable before start:

`export SWT_GTK3=0`

Related https://bugs.eclipse.org/bugs/show_bug.cgi?id=486069
